CREATE TABLE IF NOT EXISTS USER_ACCOUNT (
	USER_NAME TEXT NOT NULL,
	EMAIL_ID TEXT NOT NULL,
	MOBILE_NUMBER BIGINT NOT NULL,
	CLIENT_ID TEXT NOT NULL,
	API_KEY TEXT NOT NULL,
	API_SECRET TEXT NOT NULL,
	TOTP_SECRET_KEY TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	MAX_PROFIT_PER_DAY BIGINT NOT NULL DEFAULT 3000,
	IS_DEBUG BOOLEAN DEFAULT TRUE,
	IS_MASTER BOOLEAN DEFAULT FALSE,
	IS_TRADE_ALLOWED BOOLEAN DEFAULT FALSE,
	TELEGRAM_TOKEN TEXT NOT NULL,
	TELEGRAM_CHANNEL_NAME TEXT NOT NULL,
	TELEGRAM_BOT_NAME TEXT NOT NULL,
	PRIMARY KEY (CLIENT_ID)
);

INSERT INTO USER_ACCOUNT VALUES(
		'Loganathan Mohanraj', 
		'logumohan@gmail.com', 
		9500086681, 
		'KPT065', 
		'tffycu9szdjrrrh0', 
		'sn6iwz9ux0qyakm1kt5ycp3tv4g9mc39', 
		'KPDTBHFGE6DXPDBLNGMUGKXO2J6ACAY7', 
		'Pass4log$', 
		3000,
		true, 
		true, 
		true,
		'6058322384:AAFlroA1Yhz8tKt_-Sksx5sDUJ2uLbfdenM',
		'-1001854151286',
		'SigGen_Bot')
	ON CONFLICT (CLIENT_ID) DO 
	UPDATE SET 
		USER_NAME = excluded.USER_NAME,
		EMAIL_ID = excluded.EMAIL_ID,
		MOBILE_NUMBER = excluded.MOBILE_NUMBER,
		API_KEY = excluded.API_KEY,
		API_SECRET = excluded.API_SECRET,
		TOTP_SECRET_KEY = excluded.TOTP_SECRET_KEY,
		PASSWORD = excluded.PASSWORD,
		MAX_PROFIT_PER_DAY = excluded.MAX_PROFIT_PER_DAY,
		IS_DEBUG = excluded.IS_DEBUG,		
		IS_MASTER = excluded.IS_MASTER, 
    	IS_TRADE_ALLOWED = excluded.IS_TRADE_ALLOWED,
		TELEGRAM_TOKEN = excluded.TELEGRAM_TOKEN,
		TELEGRAM_CHANNEL_NAME = excluded.TELEGRAM_CHANNEL_NAME,
		TELEGRAM_BOT_NAME = excluded.TELEGRAM_BOT_NAME;
/*
INSERT INTO USER_ACCOUNT VALUES(
		'Rajesh', 
		'rajesh@gmail.com', 
		9500086681, 
		'ZHN652', 
		'om76v0oevmecq4is', 
		'x0qa5cydstopdttq46au83ht4m9mcph9', 
		'VQ5SQLXQCU4WB4T2OL33EZ5ZQ46JD4GC', 
		'MonkRole1949', 
		3000,
		true, 
		false, 
		false,
		'5987627256:AAEJBnmwd_9nnXuA2Rb_2P86rEU1Dz6xf9c',
		'-1001790614165',
		'signalstats_bot')
	ON CONFLICT (CLIENT_ID) DO 
	UPDATE SET 
		USER_NAME = excluded.USER_NAME,
		EMAIL_ID = excluded.EMAIL_ID,
		MOBILE_NUMBER = excluded.MOBILE_NUMBER,
		API_KEY = excluded.API_KEY,
		API_SECRET = excluded.API_SECRET,
		TOTP_SECRET_KEY = excluded.TOTP_SECRET_KEY,
		PASSWORD = excluded.PASSWORD,
		MAX_PROFIT_PER_DAY = excluded.MAX_PROFIT_PER_DAY,
		IS_DEBUG = excluded.IS_DEBUG,		
		IS_MASTER = excluded.IS_MASTER, 
    	IS_TRADE_ALLOWED = excluded.IS_TRADE_ALLOWED,
		TELEGRAM_TOKEN = excluded.TELEGRAM_TOKEN,
		TELEGRAM_CHANNEL_NAME = excluded.TELEGRAM_CHANNEL_NAME,
		TELEGRAM_BOT_NAME = excluded.TELEGRAM_BOT_NAME;

INSERT INTO USER_ACCOUNT VALUES(
		'Aarthi', 
		'aarthi.natarajan28@gmail.com', 
		9884207056, 
		'UBA677', 
		'jszdsd11tq45q597', 
		'vi41damk7bj7rd5eb8cehvhh0utf4oy8', 
		'MVD5XWYRPJPDFRO4I4HXP6WLZU6JEBDZ', 
		'Raja!234', 
		3000,
		true,
		false,
		true,
		'6267857347:AAG1BA_Hqtkg9fiSZ5Gp2XIrVabOY3KXDvM',
		'-1001801878851',
		'aarthi_signalsbot')
	ON CONFLICT (CLIENT_ID) DO 
	UPDATE SET 
		USER_NAME = excluded.USER_NAME,
		EMAIL_ID = excluded.EMAIL_ID,
		MOBILE_NUMBER = excluded.MOBILE_NUMBER,
		API_KEY = excluded.API_KEY,
		API_SECRET = excluded.API_SECRET,
		TOTP_SECRET_KEY = excluded.TOTP_SECRET_KEY,
		PASSWORD = excluded.PASSWORD,
		MAX_PROFIT_PER_DAY = excluded.MAX_PROFIT_PER_DAY,
		IS_DEBUG = excluded.IS_DEBUG,		
		IS_MASTER = excluded.IS_MASTER, 
    	IS_TRADE_ALLOWED = excluded.IS_TRADE_ALLOWED,
		TELEGRAM_TOKEN = excluded.TELEGRAM_TOKEN,
		TELEGRAM_CHANNEL_NAME = excluded.TELEGRAM_CHANNEL_NAME,
		TELEGRAM_BOT_NAME = excluded.TELEGRAM_BOT_NAME;
*/

CREATE TABLE IF NOT EXISTS INSTRUMENT_SUBSCRIPTION (
	TOKEN BIGINT, 
	NAME TEXT, 
	OPTION_NAME TEXT,
	MINIMUM_ATR INTEGER NOT NULL CHECK (MINIMUM_ATR > 0),
	EXPIRY_DAY INTEGER NOT NULL CHECK (EXPIRY_DAY >= 0 AND EXPIRY_DAY <= 6),
	MONTHLY_EXPIRY_DAY INTEGER NOT NULL CHECK (MONTHLY_EXPIRY_DAY >= 1 AND MONTHLY_EXPIRY_DAY <= 5),
	LOT_SIZE INTEGER NOT NULL CHECK (LOT_SIZE > 0),
	STRIKE_PRICE_DELTA INTEGER NOT NULL CHECK ((NAME = 'NIFTY BANK' AND STRIKE_PRICE_DELTA % 100 = 0)
		OR (STRIKE_PRICE_DELTA % 50 = 0)),
	MIN_MACD_DIFF INTEGER NOT NULL CHECK (MIN_MACD_DIFF > 0),
	PAPER_TRADABLE BOOLEAN DEFAULT TRUE,
	TRADABLE BOOLEAN DEFAULT FALSE,
	PARALLEL_TRADES INTEGER NOT NULL CHECK (PARALLEL_TRADES > 0) DEFAULT 1,
	TRADES_PER_DAY INTEGER NOT NULL CHECK (TRADES_PER_DAY > 0) DEFAULT 3,
	FAILED_TRADES_PER_DAY INTEGER NOT NULL CHECK (FAILED_TRADES_PER_DAY > 0) DEFAULT 2,
	PRIMARY KEY (TOKEN)
);

/*
INSERT INTO INSTRUMENT_SUBSCRIPTION VALUES(
		260105, 
		'NIFTY BANK', 
		'BANKNIFTY', 
		30,
		4, 
		25,
		300,
		4,
		true,
		false,
		1,
		3,
		2)
	ON CONFLICT (TOKEN) DO 
	UPDATE SET 
		NAME = excluded.NAME,
		OPTION_NAME = excluded.OPTION_NAME,
		MINIMUM_ATR = excluded.MINIMUM_ATR,
		EXPIRY_DAY = excluded.EXPIRY_DAY,
		LOT_SIZE = excluded.LOT_SIZE,
		STRIKE_PRICE_DELTA = excluded.STRIKE_PRICE_DELTA,
		MIN_MACD_DIFF = excluded.MIN_MACD_DIFF,
		PAPER_TRADABLE = excluded.PAPER_TRADABLE,
		TRADABLE = excluded.TRADABLE,
		PARALLEL_TRADES = excluded.PARALLEL_TRADES,
		TRADES_PER_DAY = excluded.TRADES_PER_DAY,
		FAILED_TRADES_PER_DAY = excluded.FAILED_TRADES_PER_DAY;

INSERT INTO INSTRUMENT_SUBSCRIPTION VALUES(
		256265, 
		'NIFTY 50', 
		'NIFTY', 
		5,
		4, 
		50, 
		50,
		1,
		true,
		false,
		1,
		3,
		2)
	ON CONFLICT (TOKEN) DO 
	UPDATE SET 
		NAME = excluded.NAME,
		OPTION_NAME = excluded.OPTION_NAME,
		MINIMUM_ATR = excluded.MINIMUM_ATR,
		EXPIRY_DAY = excluded.EXPIRY_DAY,
		LOT_SIZE = excluded.LOT_SIZE,
		STRIKE_PRICE_DELTA = excluded.STRIKE_PRICE_DELTA,
		MIN_MACD_DIFF = excluded.MIN_MACD_DIFF,
		PAPER_TRADABLE = excluded.PAPER_TRADABLE,
		TRADABLE = excluded.TRADABLE,
		PARALLEL_TRADES = excluded.PARALLEL_TRADES,
		TRADES_PER_DAY = excluded.TRADES_PER_DAY,
		FAILED_TRADES_PER_DAY = excluded.FAILED_TRADES_PER_DAY;
		
INSERT INTO INSTRUMENT_SUBSCRIPTION VALUES(
		257801, 
		'NIFTY FIN SERVICE', 
		'FINNIFTY', 
		5,
		2, 
		40,
 		1,
		50,
		1,
		true,
		false,
		1,
		3,
		2)
	ON CONFLICT (TOKEN) DO 
	UPDATE SET 
		NAME = excluded.NAME,
		OPTION_NAME = excluded.OPTION_NAME,
		MINIMUM_ATR = excluded.MINIMUM_ATR,
		EXPIRY_DAY = excluded.EXPIRY_DAY,
		LOT_SIZE = excluded.LOT_SIZE,
		STRIKE_PRICE_DELTA = excluded.STRIKE_PRICE_DELTA,
		MIN_MACD_DIFF = excluded.MIN_MACD_DIFF,
		PAPER_TRADABLE = excluded.PAPER_TRADABLE,
		PARALLEL_TRADES = excluded.PARALLEL_TRADES,
		TRADES_PER_DAY = excluded.TRADES_PER_DAY,
		FAILED_TRADES_PER_DAY = excluded.FAILED_TRADES_PER_DAY;
*/

CREATE TABLE IF NOT EXISTS AGGREGATION_TYPE (
	NAME TEXT NOT NULL CHECK (NAME = 'ONE_MINUTE' OR NAME = 'THREE_MINUTES' OR NAME = 'FIVE_MINUTES' OR 
		NAME = 'FIFTEEN_MINUTES' OR NAME = 'ONE_HOUR' OR NAME = 'ONE_DAY'),
	DURATION INTEGER,
	AGGREGABLE BOOLEAN,
	PRIMARY KEY (NAME)
);

INSERT INTO AGGREGATION_TYPE VALUES(
		'ONE_MINUTE',
		60,
		true)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;
		
INSERT INTO AGGREGATION_TYPE VALUES(
		'THREE_MINUTES',
		180,
		true)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;
		
INSERT INTO AGGREGATION_TYPE VALUES(
		'FIVE_MINUTES',
		300,
		false)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;
		
INSERT INTO AGGREGATION_TYPE VALUES(
		'FIFTEEN_MINUTES',
		900,
		false)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;
		
INSERT INTO AGGREGATION_TYPE VALUES(
		'ONE_HOUR',
		3600,
		false)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;
		
INSERT INTO AGGREGATION_TYPE VALUES(
		'ONE_DAY',
		86400,
		false)
	ON CONFLICT (NAME) DO 
	UPDATE SET 
		DURATION = excluded.DURATION,
		AGGREGABLE = excluded.AGGREGABLE;

CREATE TABLE IF NOT EXISTS JOBS (
	NAME TEXT NOT NULL,
	USER_NAME TEXT NOT NULL,
	JOB_TYPE TEXT NOT NULL CHECK (JOB_TYPE = 'ATR_TSL' OR JOB_TYPE = 'FIXED_TSL' OR JOB_TYPE = 'FIXED_PROFIT' OR JOB_TYPE = 'MULTI_TARGET'),
	STRATEGY TEXT,
	TRAILING_STRATEGY TEXT NOT NULL CHECK (TRAILING_STRATEGY = 'DEFAULT' OR TRAILING_STRATEGY = 'SIMPLE' OR TRAILING_STRATEGY = 'PROTECTIVE' 
		OR TRAILING_STRATEGY = 'AGGRESSIVE' OR TRAILING_STRATEGY = 'CUSTOM1' OR TRAILING_STRATEGY = 'MULTI_TARGET'),
	TRAIL_BY TEXT NOT NULL CHECK ((JOB_TYPE = 'ATR_TSL' AND TRAIL_BY = 'ATR') OR 
		((JOB_TYPE = 'FIXED_TSL' OR JOB_TYPE = 'FIXED_PROFIT' OR JOB_TYPE = 'MULTI_TARGET') AND TRAIL_BY = 'POINTS')),
	ATR INTEGER CHECK((JOB_TYPE = 'ATR_TSL' AND ATR > 0) OR ATR = 0),
	ATR_MULTIPLIER DECIMAL CHECK((JOB_TYPE = 'ATR_TSL' AND ATR_MULTIPLIER > 0) OR ATR_MULTIPLIER = 0),
	AGGREGATION_TYPE TEXT NOT NULL CHECK (AGGREGATION_TYPE = 'ONE_MINUTE' OR AGGREGATION_TYPE = 'THREE_MINUTES' OR 
		AGGREGATION_TYPE = 'FIVE_MINUTES' OR AGGREGATION_TYPE = 'FIFTEEN_MINUTES' OR AGGREGATION_TYPE = 'ONE_HOUR' OR 
		AGGREGATION_TYPE = 'ONE_DAY') DEFAULT 'THREE_MINUTES',
	LOT_SIZE INTEGER NOT NULL CHECK (LOT_SIZE > 0),
	TARGETS JSON CHECK(TARGETS IS NOT NULL),
	STRIKE_PRICE_DELTA INTEGER NOT NULL CHECK (STRIKE_PRICE_DELTA % 10 = 0) DEFAULT 0,
	MAX_VIX_ALLOWED INTEGER DEFAULT 15,
	PAPER_TRADABLE BOOLEAN DEFAULT TRUE,
	TRADABLE BOOLEAN DEFAULT FALSE,
	TRADABLE_DAYS TEXT[] CHECK(TRADABLE_DAYS <@ ARRAY['MON', 'TUE', 'WED', 'THU', 'FRI', 'ALL']) DEFAULT ARRAY['ALL']::TEXT[],
	
	PRIMARY KEY (NAME, USER_NAME)
);

/*
INSERT INTO JOBS VALUES(
		'FIXED_PROFIT_1K',
		'Loganathan Mohanraj',
		'FIXED_PROFIT',
		'HA_MACD',
		'PROTECTIVE',
		'POINTS',
		0,
		0,
		30,
		60,
		1000,
		'THREE_MINUTES',
		1,
		true,
		'[{"tid": 1, "size": 4, "profit": 300}]'
		100,
		15,
		true,
		false)
	ON CONFLICT (NAME, USER_NAME) DO 
	UPDATE SET
		JOB_TYPE = excluded.JOB_TYPE, 
		STRATEGY = excluded.STRATEGY,
		TRAIL_BY = excluded.TRAIL_BY,
		ATR = excluded.ATR,
		ATR_MULTIPLIER = excluded.ATR_MULTIPLIER,
		INITIAL_TSL_POINTS = excluded.INITIAL_TSL_POINTS,
		FIXED_TSL_POINTS = excluded.FIXED_TSL_POINTS,
		MIN_PROFIT = excluded.MIN_PROFIT,
		AGGREGATION_TYPE = excluded.AGGREGATION_TYPE,
		NO_OF_LOTS = excluded.NO_OF_LOTS,
		TARGETS = excluded.TARGETS,
		STRIKE_PRICE_DELTA = excluded.STRIKE_PRICE_DELTA,
		MAX_VIX_ALLOWED = excluded.MAX_VIX_ALLOWED,
		PAPER_TRADABLE = excluded.PAPER_TRADABLE,
		TRADABLE = excluded.TRADABLE;
*/

CREATE TABLE IF NOT EXISTS SIGNAL (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	AGGREGATION_TYPE TEXT,
	STRATEGY TEXT,
	SIGNAL TEXT,
	LTP DECIMAL,
	ATR DECIMAL,
	VIX DECIMAL,
	STRIKE_PRICE BIGINT,
	OPTION_SYMBOL TEXT,
	PRIMARY KEY (TICKTIME, TOKEN, AGGREGATION_TYPE, STRATEGY)
);

CREATE TABLE IF NOT EXISTS TRADE (
	TICKTIME TIMESTAMP, 
	TRADE_ID TEXT,
	USER_NAME TEXT NOT NULL,
	JOB_NAME TEXT,
	IS_LIVE BOOLEAN,
	IS_ACTIVE BOOLEAN,
	TOKEN BIGINT, 
	NAME TEXT, 
	AGGREGATION_TYPE TEXT,
	STRATEGY TEXT,
	SIGNAL TEXT,
	LTP DECIMAL,
	ATR DECIMAL,
	STRIKE_PRICE BIGINT,
	OPTION_SYMBOL TEXT,
	LOT_SIZE INTEGER NOT NULL CHECK (LOT_SIZE > 0),
	ORDER_ID TEXT,
	SL_ORDER_ID TEXT,
	PRIMARY KEY (TICKTIME, TRADE_ID, TOKEN)
);

CREATE TABLE IF NOT EXISTS POSITION (
	TRADE_ID TEXT NOT NULL,
	TID INTEGER,
	NO_OF_LOTS INTEGER NOT NULL CHECK (NO_OF_LOTS > 0),
	QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
	SOLD_QUANTITY INTEGER NOT NULL DEFAULT 0,
	ENTRY_TIME TIMESTAMP,
	EXIT_TIME TIMESTAMP,
	ENTRY_PRICE DECIMAL,
	EXIT_PRICE DECIMAL,
	OPTION_ENTRY_LTP DECIMAL,
	OPTION_EXIT_LTP DECIMAL,
	OPTION_ENTRY_PRICE DECIMAL,
	OPTION_EXIT_PRICE DECIMAL,
	UNREALIZED_PROFIT DECIMAL,
	UNREALIZED_LOSS DECIMAL,
	PROFIT DECIMAL,
	ACTIVE BOOLEAN,
	CLOSED BOOLEAN,
	SQUARE_OFF BOOLEAN,
	STOP_LOSS BOOLEAN,
	SL_PRICE DECIMAL,
	SL_TRAIL JSON,
	PRIMARY KEY (TRADE_ID, TID)
);

CREATE TABLE IF NOT EXISTS INSTRUMENT (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	PRIMARY KEY (TICKTIME, TOKEN)
);

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

SELECT CREATE_HYPERTABLE('instrument', 'ticktime', chunk_time_interval => interval '1 day', if_not_exists => TRUE);

CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_ONEMIN WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '1 minute', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;

CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_THREEMIN WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '3 minutes', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;

/*
CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_FIVEMIN WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '5 minutes', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;

CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_FIFTEENMIN WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '15 minutes', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;

CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_ONEHOUR WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '1 hour', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;

CREATE MATERIALIZED VIEW IF NOT EXISTS INSTRUMENT_DAILY WITH (TIMESCALEDB.CONTINUOUS) AS 
SELECT TIME_BUCKET(INTERVAL '1 day', TICKTIME) AS BUCKET_TICKTIME, 
	TOKEN, 
	NAME, 
	FIRST(LTP, TICKTIME) AS OPEN, 
	MAX(LTP) AS HIGH,  
	MIN(LTP) AS LOW, 
	LAST(LTP, TICKTIME) AS CLOSE,
	LAST(LTP, TICKTIME) AS LTP, 
	SUM(VOLUMETRADED) AS VOLUMETRADED, 
	SUM(TOTBUYQTY) AS TOTBUYQTY, 
	SUM(TOTSELLQTY) AS TOTSELLQTY 
FROM INSTRUMENT GROUP BY BUCKET_TICKTIME, TOKEN, NAME;
*/

CREATE TABLE IF NOT EXISTS INSTRUMENT_ONEMIN_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);

CREATE TABLE IF NOT EXISTS INSTRUMENT_THREEMIN_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);

/*
CREATE TABLE IF NOT EXISTS INSTRUMENT_FIVEMIN_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);

CREATE TABLE IF NOT EXISTS INSTRUMENT_FIFTEENMIN_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);

CREATE TABLE IF NOT EXISTS INSTRUMENT_ONEHOUR_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);

CREATE TABLE IF NOT EXISTS INSTRUMENT_DAILY_INDICATORS (
	TICKTIME TIMESTAMP, 
	TOKEN BIGINT, 
	NAME TEXT, 
	OPEN DECIMAL, 
	HIGH DECIMAL, 
	LOW DECIMAL, 
	CLOSE DECIMAL, 
	HAOPEN DECIMAL, 
	HAHIGH DECIMAL, 
	HALOW DECIMAL, 
	HACLOSE DECIMAL, 
	LTP DECIMAL, 
	VOLUMETRADED BIGINT, 
	TOTBUYQTY DECIMAL, 
	TOTSELLQTY DECIMAL, 
	HLC3 DECIMAL,
	ZLEMA_34 DECIMAL,
	SMMA_HP_34 DECIMAL,
	SMMA_LP_34 DECIMAL,
	MACD DECIMAL,
	MACD_SIGNAL DECIMAL,
	IMACD DECIMAL,
	IMACD_SIGNAL DECIMAL,
	EMA10 DECIMAL,
	EMA20 DECIMAL,
	EMA30 DECIMAL,
	EMA50 DECIMAL,
	RSI DECIMAL,
	STOCHASTICRSI DECIMAL,
	ATR DECIMAL,
	ATRTS DECIMAL,
	PRIMARY KEY (TICKTIME, TOKEN)
);
*/